language: go
go:
- 1.12.x
env:
- GO111MODULE=on
- RUN_DOCKER_MODE=on
services: consul
install:
- go get github.com/micro/protoc-gen-micro
before_script:
#- consul agent -dev
script:
- pwd
- cd service-config-push
- go mod tidy
- go run main.go loader.go