language: go
go:
- 1.12.x
env:
- GO111MODULE=on
services: consul
install:
- go get -t ./...
- go get github.com/micro/protoc-gen-micro
before_script:
- consul agent -dev
script:
- go test -v -mod=vendor ./...