os: linux
sudo: required
language: go
go:
- 1.12.x
- 1.13.x
env:
- GO111MODULE=on
#services: consul
services:
    - docker
install:
- go get github.com/micro/protoc-gen-micro
#before_script:
#- docker run -d --name=consul2 consul
#- consul agent -dev
script:
- pwd
- cd ..
- sudo mv ./travisTest /home
- cd /home/travisTest
- pwd
- docker run consul version
- docker run consul agent -dev -http-port=8500  -client=127.0.0.1 -bind=127.0.0.1
- cd service-config-push
- pwd
- go mod tidy
- go run main.go loader.go