os: linux
sudo: true
language: go
go:
- 1.12.x
env:
- GO111MODULE=on
- RUN_DOCKER_MODE=on
services: consul
install:
- go get github.com/micro/protoc-gen-micro
before_script:
#- consul agent -dev
script:
- pwd
- cd ..
- mv ./travisTest /home
- cd /home/travisTest
- pwd
_ export RUN_DOCKER_MODE=on
- consul agent -dev -http-port 8500&
- cd service-config-push
- lsof -i:8500
- pwd
- go mod tidy
- go run main.go loader.go