os: linux
sudo: required
language: go
go:
- 1.12.x
- 1.13.x
env:
- GO111MODULE=on
services: consul
install:
- go get github.com/micro/protoc-gen-micro
before_script:
#- consul agent -dev
script:
- pwd
- cd ..
- sudo mv ./travisTest /home
- cd /home/travisTest
- pwd
- consul agent -dev -http-port 8500  -client 127.0.0.1&
- cd service-config-push
- lsof -i tcp:8500
- pwd
- go mod tidy
- go run main.go loader.go