os: linux
sudo: required
language: go
go:
- 1.12.x
env:
- GO111MODULE=on
#services: consul
services:
    - docker
install:
- go get github.com/micro/protoc-gen-micro
#before_script:
#- docker run -d --name=consul2 consul
#- consul agent -dev
script:
- cd ..
- sudo mv ./travisTest /home
- cd /home/travisTest
- docker run consul version
- docker run -d -p 8500:8500 consul agent -node=node4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
- cd service-config-push
#- go mod tidy
- export IF_TRAVIS=yes
- go run -mod=vendor  main.go loader.go